name: PR Dependency Review

on:
  workflow_call:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run Dependency Review
        uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}