name: PR Dependency Review

on:
  workflow_call:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run Dependency Review
        uses: actions/dependency-review-action@56339e523c0409420f6c2c9a2f4292bbb3c07dd3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}