name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release (major, minor, patch)'
        required: false
        type: string
        default: ''

jobs:
  release:
    permissions:
      contents: write
    uses: ./.github/workflows/semantic_release.yml
    with:
      release_type: ${{ github.event_name == 'workflow_dispatch' && inputs.release_type || '' }}
